const q=s=>document.querySelector(s),qa=s=>document.querySelectorAll(s);
const h=q('.hero h1');if(h)h.innerHTML='Capacitación tecnológica gratuita<br><span>para abrir nuevas oportunidades.</span>';
const intro=q('.hero .intro');if(intro)intro.textContent='Pakova acompaña a personas de Rosario que quieren aprender informática, acercarse al mundo IT y crecer junto a su comunidad.';
const le=q('#capacitaciones .eyebrow');if(le)le.textContent='01 / QUÉ HACEMOS';const lt=q('#capacitaciones h2');if(lt)lt.innerHTML='Aprendé tecnología<br>desde tu comunidad.';
const hist=q('#historia');if(hist){const s=document.createElement('section');s.className='section';s.innerHTML='<div class="section-heading"><div><p class="eyebrow">NUESTRO PROPÓSITO</p><h2>La inclusión digital<br>también abre puertas.</h2></div><p>Formación, herramientas y oportunidades reales para jóvenes de Rosario.</p></div><div class="learning-grid"><article class="feature-card"><div class="tag">MISIÓN</div><h3>Formación que se transforma en oportunidades.</h3><p>Capacitación en competencias digitales, presencial y virtual, con puentes hacia organizaciones y empresas.</p></article><article class="next-card"><div class="tag">HISTORIA</div><h3>Un proyecto que sigue creciendo.</h3><p>Nació en 2022, se formalizó en 2023 y hoy reúne a 12 colaboradores.</p></article></div>';hist.before(s)}
const slogan=q('.manifesto p');if(slogan)slogan.textContent='Aprender. Conectar. Avanzar.';
const icons=['<svg viewBox="0 0 24 24"><path d="M12 3v18M3 12h18"/></svg>','<svg viewBox="0 0 24 24"><path d="M4 19V5m0 14h16M8 15l3-4 3 2 5-7"/></svg>','<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3"/><path d="M5 21c1-4 3-5 7-5s6 1 7 5"/></svg>'];qa('.join-grid article').forEach((c,i)=>{const b=document.createElement('span');b.innerHTML=icons[i]||icons[0];b.style.cssText='display:grid;place-items:center;width:44px;height:44px;border:1px solid #ffd600;border-radius:50%;color:#ffd600;margin-bottom:18px';b.firstChild.style.cssText='width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.6';c.prepend(b)});
const si={instagram:'◎',facebook:'f',linkedin:'in'};qa('footer a').forEach(a=>{const t=a.textContent.toLowerCase(),k=t.includes('instagram')?'instagram':t.includes('facebook')?'facebook':t.includes('linkedin')?'linkedin':null;if(k&&!a.dataset.icon){a.dataset.icon=1;a.insertAdjacentHTML('afterbegin','<span style="display:inline-grid;place-items:center;width:32px;height:32px;border:1px solid #ffd600;border-radius:50%;color:#ffd600;margin-right:8px;font-weight:700">'+si[k]+'</span>')}});
const st=document.createElement('style');st.textContent=':root{--yellow:#ffd600}body{background:#111;color:#fff}h1{font-size:clamp(32px,6vw,58px)}h2{font-size:clamp(30px,4vw,42px)}h3{font-size:24px}.feature-card,.next-card,.join-grid article{background:#171717;border-color:#3a3a3a}a{color:#fff}.button,.cta{background:#ffd600;color:#000}';document.head.append(st);
const base=q('#sumate');if(base&&!q('#alcance')){const sec=document.createElement('section');sec.id='alcance';sec.className='section';sec.innerHTML='<div class="section-heading"><div><p class="eyebrow">05 / IMPACTO</p><h2>Una red que conecta<br><span>aprendizaje y futuro.</span></h2></div><p>Pakova trabaja por la inclusión digital y la movilidad social, acercando formación a jóvenes en situación de vulnerabilidad económica.</p></div><div class="learning-grid"><article class="feature-card"><div class="tag">MISIÓN</div><h3>Puentes hacia el trabajo.</h3><p>Desarrollamos oficios y competencias digitales, articulando con organizaciones sociales y empresas para que la formación se convierta en empleo digno.</p></article><article class="next-card"><div class="tag">VISIÓN</div><h3>Tecnología con lugar para todas las personas.</h3><p>Queremos ser una organización referente en Argentina por construir un ecosistema tecnológico inclusivo.</p></article></div><div class="partners" style="margin-top:28px"><span><strong>Rosario</strong><br>Trabajo territorial</span><span><strong>Córdoba 1330</strong><br>Piso 7 · Oficina 1</span><span><strong>Presencial + virtual</strong><br>Acompañamiento cercano</span></div>';base.before(sec)}
